spring.application.name=reddit

spring.datasource.url=jdbc:mysql://mysql-cdb5003-chaurasiya-0b5d.a.aivencloud.com:17702/defaultdb?ssl-mode=REQUIRED&useSSL=true&requireSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Cloudinary - apne values daalo
cloudinary.cloud-name=deqdpks2w
cloudinary.api-key=623289558357938
cloudinary.api-secret=your_password

# Photo + Video ke liye size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000
